# Generated by Django 5.0.7 on 2024-07-31 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0003_alter_profile_middle_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
