# Generated by Django 5.0.7 on 2024-08-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0002_reviews_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='free_delivery',
            new_name='freeDelivery',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
