# Generated by Django 5.0.7 on 2024-08-11 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_rename_free_delivery_product_freedelivery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specification',
            name='product',
        ),
        migrations.AddField(
            model_name='specification',
            name='product',
            field=models.ManyToManyField(related_name='specifications', to='shopapp.product'),
        ),
    ]
