# Generated by Django 5.0.7 on 2024-08-25 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopapp', '0007_remove_product_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('deliveryType', models.CharField(choices=[('free', 'Free Delivery'), ('paid', 'Paid Delivery')], default='free', max_length=10)),
                ('paymentType', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline')], default='online', max_length=10)),
                ('totalCost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='accepted', max_length=10)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('products', models.ManyToManyField(related_name='orders', to='shopapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
