# Generated by Django 5.0.7 on 2024-09-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentError',
            field=models.CharField(default='undefined', max_length=50),
        ),
    ]
