# Generated by Django 5.0.7 on 2024-08-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='totalCost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
