# Generated by Django 5.0.7 on 2024-09-01 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordersapp', '0002_order_paymenterror'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paymentError',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
